version: '3.4'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redisdataDev:/data
    ports:
      - 6379:6379

  db:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE_TEST}
    volumes:
      - ./mysqlDataDev:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

  api_chat_dev:
    container_name: api_chat_dev
    build:
      args:
        - NODE_ENV=development
      context: .
      dockerfile: Dockerfile
      target: development
    image: api_chat_dev
    entrypoint: ["/bin/sh", "./src/scripts/entrypoint_dev.sh"]
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
      - 3001:3001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
