version: '3.4'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redisdata:/usr/src/app/redisdata
    ports:
      - 6379:6379

  db:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./mysqlData:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

  api_chat_prod:
    container_name: api_chat_prod
    build:
      args:
        - NODE_ENV=production
      context: .
      dockerfile: Dockerfile
      target: production
    image: api_chat_prod
    entrypoint: ["/bin/sh", "./src/scripts/entrypoint.sh"]
    volumes:
      - ./src/views:/usr/src/app/build/views
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
